<?php

/** @noinspection PhpUndefinedVariableInspection */

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use BuzzingPixel\Templating\TemplateEngine;
use MissionControlBackend\Csrf\CsrfToken;
use MissionControlBackend\Http\HtmlLayout;
use MissionControlBackend\Templating\FullPageLoading;
use MissionControlBackend\Templating\VendorCss;
use MissionControlBackend\Templating\VendorJs;
use MissionControlIdp\IdpCssJsPaths;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

/** @phpstan-ignore-next-line */
assert(is_string($emailAddress));

/** @phpstan-ignore-next-line */
assert($csrfToken instanceof CsrfToken);

$this->extends(HtmlLayout::PATH);

?>

<div
    data-react-container="password-reset-with-token"
    data-email-address="<?=$emailAddress?>"
    data-csrf-token-name-key="<?= $csrfToken->tokenNameKey ?>"
    data-csrf-token-name="<?= $csrfToken->tokenName ?>"
    data-csrf-token-value-key="<?= $csrfToken->tokenValueKey ?>"
    data-csrf-token-value="<?= $csrfToken->tokenValue ?>"
>
    <?= $this->partial(FullPageLoading::PATH) ?>
</div>

<?php

// These need to be loaded after the partial's CSS

VendorCss::addVendorPath(IdpCssJsPaths::CSS);

VendorJs::addVendorPath(IdpCssJsPaths::JS);
