<?php

/** @noinspection PhpUndefinedVariableInspection */

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use BuzzingPixel\Templating\TemplateEngine;
use MissionControlBackend\Http\HtmlLayout;
use MissionControlBackend\Templating\FullPageLoading;
use MissionControlBackend\Templating\VendorCss;
use MissionControlBackend\Templating\VendorJs;
use MissionControlIdp\IdpCssJsPaths;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

$this->extends(HtmlLayout::PATH);

?>

<div data-react-container="log-in">
    <?= $this->partial(FullPageLoading::PATH) ?>
</div>

<?php

// These need to be loaded after the partial's CSS

VendorCss::addVendorPath(IdpCssJsPaths::CSS);

VendorJs::addVendorPath(IdpCssJsPaths::JS);
