<?php

/** @noinspection PhpUndefinedVariableInspection */

declare(strict_types=1);

// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
// phpcs:disable Generic.Files.InlineHTML.Found

use BuzzingPixel\Templating\TemplateEngine;

/** @phpstan-ignore-next-line */
assert($this instanceof TemplateEngine);

/** @phpstan-ignore-next-line */
assert(is_string($resetLink));

?>

Someone requested a password reset for the account on Mission Control associated with your email address. If that was you, click this link:

<?=$resetLink?>

If you did not request this password reset, you can ignore this email.
